namespace: enqualifyapp-ai
ai_model_server:
  repository:
    image: ""
    tag: ""
    pullPolicy: IfNotPresent
smartid:
  environment:
    AI_DEBUG: "False"
    AI_DEV: "False"
    HASH_CHECK: "False"
    MODEL_IPC_TYPE: "GRPC"
    MODEL_SERVER_ADDR: "ai_model_server" #ai_model_server servisinin (ai_model_server.enqualifyapp.svc.cluster.local:8500)içerdeki adresi girilecek.
  repository:
    image: ""
    tag: ""
    pullPolicy: IfNotPresent
volumes:
  logfolder:
    persistentVolumeClaim:
      claimName: enqualifyapp-ai-log-pvc
pv:
  name: enqualify-ai-pv
  capacity: 
     storage: 200Gi
  nfs:
    server: ""
    path: "/"
pvc:
  volumeName: enqualify-ai-pv
  resources:
    requests:
      storage: 100Gi
ingressClassName: nginx
rules:
  host: enqualifyai.example.com

