apiVersion: apps/v1
kind: Deployment
metadata:
  name: aimodelserver
  namespace: {{ .Values.namespace }}
  labels:
    ai.service: aimodelserver
spec:
  replicas: 1
  selector:
    matchLabels:
      ai.service: aimodelserver
  template:
    metadata:
      labels:
        ai.service: aimodelserver
    spec:
      containers:
        - name: ai_model_server
          image: "{{ .Values.ai_model_server.repository.image }}:{{ .Values.ai_model_server.repository.tag }}"
          imagePullPolicy: {{ .Values.ai_model_server.repository.pullPolicy }}
          ports:
            - name: ai_model_server
              containerPort: 8500
            - name: ai_model_server-8501
              containerPort: 8501

