apiVersion: v1
kind: Service
metadata:
  name: aimodelserver
  namespace: {{ .Values.namespace }}
  labels:
    ai.service: aimodelserver
spec:
  selector:
    ai.service: aimodelserver
  ports:
    - name: portone
      protocol: TCP
      port: 8500
      targetPort: 8500
    - name: porttwo
      protocol: TCP
      port: 8501
      targetPort: 8501