apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: enqualifyapp-ai-log-pvc
   namespaces: {{ .Values.namespace }}
spec:
  storageClassName: ""
  volumeName: {{ .Values.pvc.volumeName }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
       storage: {{ .Values.pvc.resources.requests.storage }}
