apiVersion: v1
kind: PersistentVolume
metadata:
  name: enqualify-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.pv.capacity.storage }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.pv.nfs.server }}
    path: {{ .Values.pv.nfs.path }}